//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace poligono.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posizionis
    {
        public int ID { get; set; }
        public string Lat { get; set; }
        public string Lon { get; set; }
        public string Tipo { get; set; }
    }
}
